name: Build and Upload Artifacts

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev

      - name: Build
        run: cargo build --release

      - name: Create AppImage (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get install -y libfuse2
          wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
          chmod +x appimagetool-x86_64.AppImage
          mkdir -p AppDir/usr/bin
          cp target/release/Weave-Lunar-Launcher AppDir/usr/bin/
          cat > AppDir/AppRun << EOL
          #!/bin/sh
          exec ./usr/bin/Weave-Lunar-Launcher
          EOL
          chmod +x AppDir/AppRun
          ./appimagetool-x86_64.AppImage AppDir
          mv *.AppImage Weave-Lunar-Launcher-linux.AppImage

      - name: Rename binary (Windows)
        if: matrix.os == 'windows-latest'
        run: mv target/release/Weave-Lunar-Launcher.exe Weave-Lunar-Launcher-windows.exe

      - name: Rename binary (macOS)
        if: matrix.os == 'macOS-latest'
        run: mv target/release/Weave-Lunar-Launcher Weave-Lunar-Launcher-macos

      - name: Upload artifact (Linux)
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v2
        with:
          name: Weave-Lunar-Launcher-linux
          path: Weave-Lunar-Launcher-linux.AppImage

      - name: Upload artifact (Windows)
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v2
        with:
          name: Weave-Lunar-Launcher-windows
          path: Weave-Lunar-Launcher-windows.exe

      - name: Upload artifact (macOS)
        if: matrix.os == 'macOS-latest'
        uses: actions/upload-artifact@v2
        with:
          name: Weave-Lunar-Launcher-macos
          path: Weave-Lunar-Launcher-macos
